import { ChurchToolsStorageProvider } from './core'

import './changeHistory.provider'
import './categories.provider'
import './assets.provider'
import './assetGroups.provider'
import './bookings.provider'
import './kits.provider'
import './maintenance.provider'
import './maintenanceCompanies'
import './stockTakes.provider'
import './savedViews.provider'
import './assetPrefixes.provider'
import './people.provider'
import './damage.provider'
import './assignment.provider'
import './models.provider'
import './masterData.provider'
import './prefixPreferences.provider'

export { ChurchToolsStorageProvider }
